name: "Reproduce setup-python cache issue"
description: "Reproduces the cache-dependency-path bug"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      # uses: actions/setup-python@v4
      
      uses: aparnajyothi-y/setup-python@enhance-cache-dependency-path
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: ${{ github.action_path }}/requirements.txt
    - name: Install Dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt