[tool.poetry]
name = "your-project-name"
version = "0.1.0"
description = "A description of your project"
authors = ["Your Name <your.email@example.com>"]



[tool.poetry.group.main.dependencies]
python = "3.13"
