name: Test pip cache

on:
  workflow_dispatch:
  push:

jobs:
  test-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - run: echo "${{ steps.python.outputs.python-version }}"

      # - run: pip install -r requirements.txt    

     

