name: Check System Architecture

on:
  workflow_dispatch:
  push:

jobs:
  test-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, windows-11-arm, macos-latest, windows-latest]
    steps:
      - name: Check System Architecture
        shell: bash
        run: |
          echo "Python platform.machine(): $(python -c 'import platform; print(platform.machine())')"
          echo "Python platform.architecture(): $(python -c 'import platform; print(platform.architecture())')"
          echo "Python platform.processor(): $(python -c 'import platform; print(platform.processor())')"
          echo "PowerShell \$env:PROCESSOR_ARCHITECTURE: $PROCESSOR_ARCHITECTURE"
          echo "PowerShell \$env:PROCESSOR_IDENTIFIER: $PROCESSOR_IDENTIFIER"

          BIRTH_NATIVE_ARCH_STRING="$(uname -m)"
          echo "uname -m: $BIRTH_NATIVE_ARCH_STRING"
