name: Test check latest

on:
  workflow_dispatch:
  # push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, ]
        python-version: ["pypy3.10", "pypy-3.11", 'pypy3.10-v7.3.17']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - run: echo "${{ steps.python.outputs.python-version }}"

     


