name: Test Hyphen Ranges Python Versions

on:
  push:
    
jobs:
 test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, windows-11-arm]
        python-version:
          - '3.12.0-alpha - 3.13.0'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: ${{ matrix.python-version }}
          pip-version: 24.1

      - name: Verify pip version
        run: pip --version

      - name: Install dependencies
        run: pip install -r requirements.txt
