name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  self-test-happy-path:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          path: sample-python

      - uses: ./sample-python