name: Test Matrix Python Versions

on:
  workflow_dispatch:
    
  push:
    branches:
      - python-freethreaded-test

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-24.04-arm, ubuntu-22.04-arm]
        python-version: ['3.13t', '3.13.1t', '3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
         # uses: actions/setup-python@v5
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
