
     
name: Node.js Package

on:
  push:
    branches:
      - pnpm-test

jobs:
  build:
    runs-on: [self-hosted, Arm64]

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Setup Node.js
      uses: priyagupta108/setup-node@fix-win-arm64-setup
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Test
      run: pnpm test

