name: Test prerelease Python 

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.14.0-beta.1', '3.14.0-alpha.1', "3.13.0-rc.3"]
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@test-pip-version
        with:
          python-version: ${{ matrix.python-version}}
          pip-version: 24.1
          cache: 'pip'

      - name: Verify pip version
        run: python -m pip --version

      - run: pip install -r requirements.txt    

     


