name: Test pypy&GraalPy Versions

on:
  workflow_dispatch:
  # push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, windows-11-arm]
        python-version: ['graalpy-24.0',  'pypy3.10']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: ${{ matrix.python-version }}
          pip-version: 24.1
     
      - name: Verify pip version
        run: pip --version

   

     


