name: Test Python Versions

on: [push, pull_request]

jobs:
  test-cached-versions:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, windows-11-arm]
        python-version: ['3.13', '3.12', '3.11', '3.10', 3.9']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@test-pip-version
        with:
          python-version: ${{ matrix.python-version }}
          pip-version: 23.1

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt    

    