name: Try to hit API Rate Limit with GITHUB_TOKEN

on:
  workflow_dispatch:
  push:

jobs:
  rate-limit:
    runs-on: ubuntu-latest
    steps:
    - name: Check starting rate limit
      run: curl -H "Authorizationtoken ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit

    - name: Flood repo API (try to exhaust limit)
      run: |
        for i in {1..5000}; do
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/priyagupta108/sample-python/contents/.github/workflows > /dev/null
        done

    - name: Check rate limit after flood
      run: curl -H "Authorizationtoken ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit

    - name: Setup Python (try to trigger rate limit error)
      uses: actions/setup-python@v6
      with:
        python-version: graalpy-24.1

    - name: Show Python version
      run: python --version
