name: Test

on: [push, pull_request, workflow_dispatch]

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# jobs:

#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:

#         python-version: ["pypy3.10", "3.13"]
#         os: [windows-latest, macos-latest, ubuntu-latest, ubuntu-22.04-arm, ubuntu-24.04-arm, macos-13]

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v5
#         # uses: mayeut/setup-python@pypy-aarch64
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Test
#         run: |
#           python --version --version

jobs:
  test:
    runs-on: self-hosted
  
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    # - name: Fix pip entries
    #   run: |
    #     python3 -m pip uninstall -y pip
    #     python3 -m ensurepip --upgrade
    #     python3 -m pip install --upgrade pip
      
    # - name: Show pip version after uninstall
    #   run: |
    #       echo "Checking pip version after uninstall:"
    #       if command -v pip3; then
    #         echo "pip3 still exists!"
    #         pip3 --version
    #         exit 1
    #       else
    #         echo "pip3 successfully removed."
    #       fi
    # - name: Force reinstall pip
    #   run: python3 -m ensurepip --upgrade
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.13.9
        pip-version: '25.0.1'
        cache: 'pip' 
        

    - name: Display Python version
      run: python --version

    - name: Check pip
      run: |
        which pip
        pip --version
