name: Test Python Version Ranges

on:
  push:
    branches:
      - python-freethreaded-test

jobs:

 test-with-t:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '>=3.9 <3.14t'
         
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
         # uses: actions/setup-python@v5
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

 test-freethreaded-true:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '>=3.9 <3.14'
         
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
         # uses: actions/setup-python@v5
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: ${{ matrix.python-version }}
          freethreaded: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

 test-default-pr:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '>=3.9 <3.14'
        
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
         # uses: actions/setup-python@v5
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

 test-default-v5:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '>=3.9 <3.14'
        
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        # uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt        