name: Validate 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
