name: Python workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Run steps with Python 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
  
      - name: Run tests
        run: pytest
      # Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Run steps with Python 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
  
      - name: Run tests
        run: pytest
