
name: SandBox

on:
  push:
  workflow_dispatch:

jobs:
  setup_python:
    name: ${{ matrix.os }} ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-13", "ubuntu-22.04", "ubuntu-20.04"]
        architecture: ["x64"]
        include:
          - os: "windows-latest"
            architecture: "x86"
          - os: "macos-14"
            architecture: "arm64"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # uses: quansight-labs/setup-python@v5
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: "3.13.1t"
          architecture: ${{ matrix.architecture }}
      - name: Set up Python
        # uses: quansight-labs/setup-python@v5
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: "3.13.1"
          architecture: ${{ matrix.architecture }}
      - name: Check python
        run: |
          set -ex
          echo "$PATH"
          if [ -d /c/hostedtoolcache/windows ]; then
              find /c/hostedtoolcache/windows/Python/3.13.1 -maxdepth 2 -name 'python*'
              py --list
          fi
          which python
          which python3
          which python3.13 || true
          which python3.13t
          python3.13 -VV || python3 -VV
          python3.13t -VV
        shell: bash
