name: Go test ci on github hosted runner

on:
  push:
    branches:
      - sample-go
  workflow_dispatch:

jobs:
  golang:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        
    steps:
      - name: Checkout gpnutil
        uses: actions/checkout@v4
     
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
      - name: Set up Python
        run: python --version
      - name: go clean
        run: go clean -modcache
      
     
      - name: Build
        run: go build -o lib.so -buildmode=c-shared

      - name: Test shared library
        run: python run.py

      - name: Save shared library as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: lib-${{ matrix.os }}
          path: lib.so
