name: Test pip unsupported version format

on:
  workflow_dispatch:
  # push:


jobs:
  test-value1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.12'
          pip-version: '!=23.1.0'
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt

  test-value2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.12'
          pip-version: '>23.0.0'
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt

  test-value3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.12'
          pip-version: '<24.0.0'
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt

  test-value4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.12'
          pip-version: '>=23.0.0'
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt

  test-value5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.12'
          pip-version: '<=23.3.1'
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt

  test-value6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.12'
          pip-version: '>=23.0.0,<24.0.0'
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt

  test-value7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.12'
          pip-version: '>=23.0.0,!=23.1.0'
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt