name: Test pip unsupported version format

on: [push, pull_request]

jobs:
  test-1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.12'
          pip-version: '!=23.1.0'
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt    

    test-2:
      runs-on: ubuntu-latest
    
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: priyagupta108/setup-python@pip-version-input
          with:
            python-version: '3.12'
            pip-version: '>23.0.0'
            cache: 'pip'

        - name: Verify pip version
          run: pip --version

        - run: pip install -r requirements.txt    

test-3:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.12'
          pip-version: '<24.0.0'
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt    
test-4:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.12'
          pip-version: '>=23.0.0'
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt    
test-5:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.12'
          pip-version: '<=23.3.1'
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt    
test-6:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.12'
          pip-version: '>=23.0.0,<24.0.0'
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt    
test-7:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.12'
          pip-version: '>=23.0.0,!=23.1.0'
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt    
