name: Test x-Ranges Python Versions

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, windows-2019-arm]
        python-version:
          - '3.x'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: priyagupta108/setup-python@test-pip-version
        with:
          python-version: ${{ matrix.python-version }}
          pip-version: 24.2
          check-latest: true

      - name: Verify pip version
        run: python -m pip --version 

      - name: Install dependencies
        run: pip install -r requirements.txt