name: Test x.y-dev Python Versions

on:
   workflow_dispatch:
   push:
    branches:
      - python-freethreaded-test

jobs:
  test-freethreaded:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '3.14t-dev'
          - '3.13t-dev'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
         # uses: actions/setup-python@v5
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test-freethreaded-true:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '3.14-dev'
          - '3.13-dev'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
         # uses: actions/setup-python@v5
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: ${{ matrix.python-version }}
          freethreaded: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test-default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '3.14-dev'
          - '3.13-dev'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
         # uses: actions/setup-python@v5
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      